### ISSUE TITLE
Define alternative picture/icon if no picture is available

### ISSUE THREAD

**Issue by MagdalenaDeschner** [washeuteessen/washeuteessen-ui#4]
https://www.chefkoch.de/rezepte/1784391288514689/Brombeer-Holunder-Likoer.html
![grafik](https://user-images.githubusercontent.com/34448387/59221977-ce28a100-8bc8-11e9-84fd-ea546fd2830a.png)

**Comment by arndt-s** [comment]
pictures wont show if no picture was found.
